// Code generated by counterfeiter. DO NOT EDIT.
package logfakes

import (
	"service/log"
	"sync"

	"go.uber.org/zap/zapcore"
)

type FakeProdInterface struct {
	InfoStub        func(msg string, fields ...zapcore.Field)
	infoMutex       sync.RWMutex
	infoArgsForCall []struct {
		msg    string
		fields []zapcore.Field
	}
	DebugStub        func(msg string, fields ...zapcore.Field)
	debugMutex       sync.RWMutex
	debugArgsForCall []struct {
		msg    string
		fields []zapcore.Field
	}
	WarnStub        func(msg string, fields ...zapcore.Field)
	warnMutex       sync.RWMutex
	warnArgsForCall []struct {
		msg    string
		fields []zapcore.Field
	}
	ErrorStub        func(msg string, fields ...zapcore.Field)
	errorMutex       sync.RWMutex
	errorArgsForCall []struct {
		msg    string
		fields []zapcore.Field
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProdInterface) Info(msg string, fields ...zapcore.Field) {
	fake.infoMutex.Lock()
	fake.infoArgsForCall = append(fake.infoArgsForCall, struct {
		msg    string
		fields []zapcore.Field
	}{msg, fields})
	fake.recordInvocation("Info", []interface{}{msg, fields})
	fake.infoMutex.Unlock()
	if fake.InfoStub != nil {
		fake.InfoStub(msg, fields...)
	}
}

func (fake *FakeProdInterface) InfoCallCount() int {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return len(fake.infoArgsForCall)
}

func (fake *FakeProdInterface) InfoArgsForCall(i int) (string, []zapcore.Field) {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return fake.infoArgsForCall[i].msg, fake.infoArgsForCall[i].fields
}

func (fake *FakeProdInterface) Debug(msg string, fields ...zapcore.Field) {
	fake.debugMutex.Lock()
	fake.debugArgsForCall = append(fake.debugArgsForCall, struct {
		msg    string
		fields []zapcore.Field
	}{msg, fields})
	fake.recordInvocation("Debug", []interface{}{msg, fields})
	fake.debugMutex.Unlock()
	if fake.DebugStub != nil {
		fake.DebugStub(msg, fields...)
	}
}

func (fake *FakeProdInterface) DebugCallCount() int {
	fake.debugMutex.RLock()
	defer fake.debugMutex.RUnlock()
	return len(fake.debugArgsForCall)
}

func (fake *FakeProdInterface) DebugArgsForCall(i int) (string, []zapcore.Field) {
	fake.debugMutex.RLock()
	defer fake.debugMutex.RUnlock()
	return fake.debugArgsForCall[i].msg, fake.debugArgsForCall[i].fields
}

func (fake *FakeProdInterface) Warn(msg string, fields ...zapcore.Field) {
	fake.warnMutex.Lock()
	fake.warnArgsForCall = append(fake.warnArgsForCall, struct {
		msg    string
		fields []zapcore.Field
	}{msg, fields})
	fake.recordInvocation("Warn", []interface{}{msg, fields})
	fake.warnMutex.Unlock()
	if fake.WarnStub != nil {
		fake.WarnStub(msg, fields...)
	}
}

func (fake *FakeProdInterface) WarnCallCount() int {
	fake.warnMutex.RLock()
	defer fake.warnMutex.RUnlock()
	return len(fake.warnArgsForCall)
}

func (fake *FakeProdInterface) WarnArgsForCall(i int) (string, []zapcore.Field) {
	fake.warnMutex.RLock()
	defer fake.warnMutex.RUnlock()
	return fake.warnArgsForCall[i].msg, fake.warnArgsForCall[i].fields
}

func (fake *FakeProdInterface) Error(msg string, fields ...zapcore.Field) {
	fake.errorMutex.Lock()
	fake.errorArgsForCall = append(fake.errorArgsForCall, struct {
		msg    string
		fields []zapcore.Field
	}{msg, fields})
	fake.recordInvocation("Error", []interface{}{msg, fields})
	fake.errorMutex.Unlock()
	if fake.ErrorStub != nil {
		fake.ErrorStub(msg, fields...)
	}
}

func (fake *FakeProdInterface) ErrorCallCount() int {
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	return len(fake.errorArgsForCall)
}

func (fake *FakeProdInterface) ErrorArgsForCall(i int) (string, []zapcore.Field) {
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	return fake.errorArgsForCall[i].msg, fake.errorArgsForCall[i].fields
}

func (fake *FakeProdInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	fake.debugMutex.RLock()
	defer fake.debugMutex.RUnlock()
	fake.warnMutex.RLock()
	defer fake.warnMutex.RUnlock()
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProdInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ log.ProdInterface = new(FakeProdInterface)
